# Generated by Django 2.1.4 on 2018-12-26 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torien', '0004_auto_20181215_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategorything',
            name='things',
        ),
    ]
